name: Auto Setup Master Branch

on:
  push:
    branches: [main]  # Triggers when repo is first created using template

jobs:
  setup:
    if: ${{ github.repository != 'teq-io-innovations/repo-template' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create master branch
        run: |
          git config --global user.name "teq.io[bot]"
          git config --global user.email "teq.io[bot]@users.noreply.github.com"
          git checkout -b master
          git push origin master

      - name: Clone and remove setup workflow from master
        env:
          GH_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
        run: |
          git clone https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} repo
          cd repo
          git checkout master
          rm .github/workflows/setup-repo.yml
          git add .
          git commit -m "Cleanup: remove setup workflow"
          git push origin master

      - name: Set master as default
        env:
          GH_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
        run: |
          gh repo edit --default-branch master

      - name: Delete main branch
        env:
          GH_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
        run: |
          gh api -X DELETE /repos/${{ github.repository }}/git/refs/heads/main

      - name: Protect master branch
        env:
          GH_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
        run: |
          cat > protection.json <<EOF
          {
            "required_status_checks": {
              "strict": true,
              "contexts": ["build"]
            },
            "enforce_admins": true,
            "required_pull_request_reviews": {
              "dismiss_stale_reviews": true,
              "require_code_owner_reviews": true
            },
            "restrictions": null
          }
          EOF

          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/branches/master/protection \
            --input protection.json